/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:a4329568-f7ba-42ab-8f36-8083f66bbc75",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_1prWwL0m7",
    "aws_user_pools_web_client_id": "2k0ju0ffc7mduggi0j4ob7lqc8",
    "oauth": {},
    "aws_cognito_login_mechanisms": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "ADDRESS",
        "PHONE_NUMBER",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    }
};


export default awsmobile;
